name = "Applications Setup"

[[data]]
name = "Communication Apps"

[[data.entries]]
name = "Discord"
description = "Discord is a versatile communication platform for gamers and communities, offering voice, video, and text chat features."
script = "discord-setup.sh"
task_list = "I"

[[data.entries]]
name = "Signal"
description = "Signal is a privacy-focused messaging app that provides end-to-end encryption for secure text, voice, and video communication."
script = "signal-setup.sh"
task_list = "I"

[[data.entries]]
name = "Slack"
description = "Slack is a collaboration platform designed for team communication, featuring channels, direct messaging, file sharing, and integrations with various productivity tools."
script = "slack-setup.sh"
task_list = "I"

[[data.entries]]
name = "Telegram"
description = "Telegram is a cloud-based messaging app known for its speed and security, offering features like group chats, channels, and end-to-end encrypted calls."
script = "telegram-setup.sh"
task_list = "I"

[[data.entries]]
name = "Thunderbird"
description = "Thunderbird is a free, open-source email client that offers powerful features like customizable email management, a built-in calendar, and extensive add-ons for enhanced functionality."
script = "thunderbird-setup.sh"
task_list = "I"

[[data.entries]]
name = "Zoom"
description = "Zoom is a widely-used video conferencing platform that allows users to host virtual meetings, webinars, and online collaboration with features like screen sharing and recording."
script = "zoom-setup.sh"
task_list = "I"

[[data]]
name = "Developer Tools"

[[data.entries]]
name = "VS Code"
description = "Visual Studio Code (VS Code) is a lightweight, open-source code editor with built-in support for debugging, version control, and extensions for various programming languages and frameworks."
script = "vscode-setup.sh"
task_list = "I"

[[data.entries]]
name = "VS Codium"
description = "VSCodium is a free, open-source version of Visual Studio Code (VS Code) that removes Microsoft-specific telemetry and branding."
script = "vscodium-setup.sh"
task_list = "I"

[[data.entries]]
name = "Sublime Text"
description = "Sublime Text is a fast, lightweight, and customizable text editor known for its simplicity, powerful features, and wide range of plugins for various programming languages."
script = "sublime-setup.sh"
task_list = "I"

[[data.entries]]
name = "Neovim"
description = "Neovim is a refactor, and sometimes redactor, in the tradition of Vim. It is not a rewrite but a continuation and extension of Vim."
script = "neovim-setup.sh"
task_list = "I FM"

[[data.entries]]
name = "Docker"
description = "Docker is a platform for developing, shipping, and running applications in containers."
script = "docker-setup.sh"
task_list = "I"

[[data.entries]]
name = "Podman"
description = "Podman is a daemonless container engine for developing, managing, and running containers on Linux systems."
script = "podman-setup.sh"
task_list = "I"

[[data]]
name = "Terminal Emulators"

[[data.entries]]
name = "Alacritty"
description = "Alacritty is a modern terminal emulator that comes with sensible defaults, but allows for extensive configuration."
script = "alacritty-setup.sh"
task_list = "I"

[[data.entries]]
name = "Kitty"
description = "Kitty is a modern, fast, feature-rich, GPU based terminal emulator."
script = "kitty-setup.sh"
task_list = "I"

[[data.entries]]
name = "Zsh"
description = "Zsh is a shell designed for interactive use, although it is also a powerful scripting language."
script = "zsh-setup.sh"
task_list = "I"

[[data]]
name = "System Tools"

[[data.entries]]
name = "FastFetch"
description = "FastFetch is a CLI tool to display information about your operating system, software and hardware."
script = "fastfetch-setup.sh"
task_list = "I"

[[data.entries]]
name = "Auto CPUFreq"
description = "Auto CPUFreq is a modern power manager for Linux systems."
script = "auto-cpufreq.sh"
task_list = "I"

[[data.entries]]
name = "Flatpak"
description = "Flatpak is a system for building, distributing and running sandboxed desktop applications on Linux."
script = "setup-flatpak.sh"
task_list = "I"

[[data.entries]]
name = "Bottles"
description = "Bottles is an easy-to-use graphical tool for managing Wine prefixes."
script = "bottles-setup.sh"
task_list = "I"

[[data.entries]]
name = "Waydroid"
description = "Waydroid is a container-based approach to boot a full Android system on a regular GNU/Linux system."
script = "waydroid-setup.sh"
task_list = "I" 