name = "System Setup"

[[data]]
name = "System Setup"

[[data.entries]]
name = "System Update"
description = "Update macOS and installed applications to the latest versions."
script = "system-update.sh"
task_list = "I"

[[data.entries]]
name = "System Cleanup"
description = "Clean up temporary files, old downloads, and system cache to free up disk space."
script = "system-cleanup.sh"
task_list = "I"

[[data.entries]]
name = "Developer Setup"
description = "Install common development tools and configure the development environment."
script = "dev-setup.sh"
task_list = "I"

[[data.entries]]
name = "SSH Setup"
description = "Configure SSH for secure remote access and file transfers."
script = "ssh.sh"
task_list = "I"

[[data.entries]]
name = "Remove Animations"
description = "Remove system animations to improve performance on older hardware."
script = "remove-animations.sh"
task_list = "I"

[[data.entries]]
name = "Fix Finder"
description = "Fix common Finder issues and improve performance."
script = "fix-finder.sh"
task_list = "I"

[[data.entries]]
name = "Touch ID Setup"
description = "Configure Touch ID for secure authentication."
script = "touch-id.sh"
task_list = "I"

[[data.entries]]
name = "Trackpad Setup"
description = "Configure trackpad settings for optimal performance."
script = "trackpad-setup.sh"
task_list = "I" 